export const arraySetor = [
    'Retail Trade',
    'Energy Minerals',
    'Health Services',
    'Utilities',
    'Finance',
    'Consumer Services',
    'Consumer Non-Durables',
    'Non-Energy Minerals',
    'Commercial Services',
    'Distribution Services',
    'Transportation',
    'Technology Services',
    'Process Industries',
    'Communications',
    'Producer Manufacturing',
    'null',
    'Miscellaneous',
    'Electronic Technology',
    'Industrial Services',
    'Health Technology',
    'Consumer Durables'
]